server:
  port: 8080

spring:
  application:
    name: engolearn
  config:
    import: optional:file:.env[.properties]
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${APP_DB:engolearn_db}
    username: ${APP_USER:admin}
    password: ${APP_PASSWORD:admin123}